project:
  type: book
  output-dir: docs

book:
  title: "Stat468_Final"
  author: "Trevor Steunenberg"
  date: "2025-07-12"
  chapters:
    - index.qmd
    - question.qmd
    - 1_import.qmd
    - 2_tidy.qmd
    - 3_transform.qmd
    - 4_visualize.qmd
    - 5_model.qmd
    - 6_communicate.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

