---
title: "Communicate"
author: "Trevor S"
---

This is a placeholder for my communicate chapter and will eventually have plots, tables, etc.

This chapter will contain my table, graph, value + pick functions, and instructions for and a link to my shiny app. In my RShiny app, I plan to allow users to enter potential trades, click "evaluate", and then see the point gain/loss. Additionally, I'd like to put the point difference into context "this is equivalent to team A giving up the 174th overall pick".

Other things I need to do:

-   Read thru instructions to see if I'm missing anything

-   Give all plots titles and labels

-   Remove unnecessary library calls

-   Make sure everything flows logically

-   Make notation consistent

-   make sure links work

-   Make code more efficient

-   Spell check

-   Add references to .bib file

-   remove unnecessary files from github (ie holding_file, model2, etc).

3 team trades are incredibly rare in the NHL so they are not directly included in the app, though they could be analyzed by looking at what each team individually receives and gives up (ie look at it in terms of 3 two team trades)

This is all the code that I think might be useful but that I currently don't know what it is for.

```{r, eval = FALSE}
# I couldn't find any info online about the error I was getting so I used 
#   ChatGPT, it turns out vetiver does not work with nls objects, so for
#   now I'm using one of the linear models

# v <- vetiver_model(nls_scal_ps, "ps_value_model")

v <- vetiver_model(lin_models[[1]], "lm_test")

model_board <- board_folder("/data/model")
model_board |>
  vetiver_pin_write(v)

model_board |> 
  vetiver_pin_read("lm_test")




test_lm <- lm(ps ~ overall, data = all_data_adj)
v <- vetiver_model(test_lm, "test_lm")




model_board <- board_temp(versioned = TRUE)
model_board |> 
  vetiver_pin_write(v)



pr() |>
  vetiver_api(v) |> 
  pr_run(port = 8080)
```
