# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_s3(bucket = "trevor-stat468", region = "us-east-2")
v <- vetiver_pin_read(b, "logist_model", version = "20250807T232740Z-69ecb")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
