---
title: "Question"
author: "Trevor S"
---

## Approach

Depending on the context, there can be countless approaches one could take to define the relative value of each selection of an NHL Entry Draft. As one example, one could look at prior trades and then define the value of a pick to be what it has historically been traded for (the "market rate"), as was done by @isacke_examining_2022 and @tulsky_nhl_2013. For example, this approach might say that pick $i$ is typically traded for pick $j$ and pick $k$. This means that. This is **not** the approach we will take.

In contrast, this report will take the approach of defining the value of selection $i$ to be the typical career contribution of players drafted at $i^{\text{th}}$ overall (we will define what "contribution" means when we pick a model). This matches the definition chosen by @moreau_valuation_2025 (NHL), @cacchione_mlb_2018 (MLB), and @liner_determining_2020 (NBA) and is preferred in this context because we wish to find opportunities for general managers to make trades that help their team make trades which allow them to draft higher quality players. Using this definition of value will help NHL General Managers make data-backed decisions as opposed to using past trades as a starting point in trade negotiations. This is preferable since previous trades could be based on what "feels" favourable instead of what is favourable. Furthermore, in context of trades which only include draft picks, one team usually gets the better end of the trade. In other words, basing trades off what "feels" favourable doesn't make a whole lot of sense because draft pick exchanges are typically only favourable to one team, not both.

This report will estimate $v_i$ by fitting several regression models incorporating player contribution data by the players previously selected at pick $i$. We will consider GP and PS as our metrics for measuring player quality (and thus the quality of a pick), and for most of them we will fit a linear and non-linear regression model.

The first two methods of evaluating player quality are similar to approaches taken by @moreau_valuation_2025, @cacchione_mlb_2018, and @liner_determining_2020, and will take the PS (or GP) of all players taken at pick $i$. Next, will consider a similar metric which adjusts the PS values for active players based on what we estimate their PS will be at the time of their retirement. The final approach is from @luo_improving_2024, and will define an indicator random variable $Z_{ij} = 1$ if and only if the player selected at pick $i$ of draft $j$ became, or is on track to become, an NHL regular. We will then fit a logistic regression model, giving us an estimate of the probability that a player selected at pick $i$ will become an NHL regular. Thus in total we have four measures of the quality which will be considered: PS, GP, adjusted PS, and probability of becoming an NHL regular.

## About Point Share (PS)

Point Share is a metric which aims to mimic Bill James' Win Shares which was used to evaluate player contributions in the MLB @kubatko_calculating_nodate. We will look at the distribution of our dataset's PS values in the Visualize chapter, but PS itself is a good metric to use for a few reasons:

-   As it turns out, the distribution of PS values is much more skewed than the distribution of GP values. Though we won't show this, it makes sense that this means PS is better at distinguishing between the quality of players than GP is.

-   The formula for PS uses the number of goals in the league in a given season, so players who play in lower scoring eras will get more credit for their goals than players who play in eras with more scoring league wide.

-   PS also adjusts for the quality of a player's team by comparing their team's scoring record with and without a player on the ice. This is also how it attempts to measure a player's defensive contributions.

There are a few concerns about using PS:

-   Using goals against to measure a player's defensive ability is dubious because it is largely dependent or the quality of their goalie.

-   From an offensive perspective, it also does not adjust for quality of linemates or the quality of the opponent.

## Considerations

We will fit 7 models in the Model chapter, so we need some criteria for what a feasible model looks like. We define a feasible model to be a model which satisfies **both** of the following:

-   $v_i > v_{i+k}$ for all $i, k \in \mathbb Z^+$

    -   This ensures later draft picks are not considered more valuable than picks earlier in the draft. This should intuitively make sense because the players available at pick $i+k$ are a proper subset of the players available at pick $i$, so there is no reason for a later pick to be more valuable in a trade context than an earlier pick.

-   $v_i > 0$ for all $i \in \mathbb Z^+$

    -   Every pick has a positive value since there is no real negative impact to picking a bad player, other than the opportunity cost of the "wasted" draft pick. Even if a player plays in NHL games and objectively contributes negatively to their team, this report takes the stance that the player has zero value instead of a negative value.

While we will not include it in the definition of a feasible model, it is common knowledge in ice hockey circles (and confirmed by the previous work listed below) that NHL draft picks do **not** decrease in value linearly. In particular, $v_i$ decreases quickly in $i$, so the difference in value pick 1 and 30 is much greater than between pick 101 and 130 (ie $v_1 - v_{30} >>> v_{101} - v_{130}$). In the Model chapter we will fit this model and show that it is not appropriate, before quickly moving on to non-linear models.

Note that if picks did decrease linearly in value linearly then it would be very easy to create a model of draft pick value since we would have

$$ v_1 = v_2 + c = v_3 + 2c = ... = v_{224} + 223c $$

where $c > 0$, meaning we would only have to find the value of $c$.

## Previous Work

Some work in this area has been done before, such as:

-   [Valuation of NHL Draft Picks using Functional Data Analysis](https://summit.sfu.ca/_flysystem/fedora/2023-02/etd22223.pdf) (@moreau_valuation_2025)

-   [MLB Rule IV Draft: Valuing Draft Pick Slots](https://academicworks.cuny.edu/cgi/viewcontent.cgi?article=1759&context=cc_etds_theses) (@cacchione_mlb_2018)

-   [Determining the Value of NBA Draft Picks using Advanced Statistics](https://repository.arizona.edu/handle/10150/651330) (@liner_determining_2020)

-   [Examining the value of NHL Draft picks](https://soundofhockey.com/2022/06/06/examining-the-value-of-nhl-draft-picks/amp/) (@isacke_examining_2022)

-   [NHL draft: What does it cost to trade up?](https://www.broadstreethockey.com/post/nhl-draft-pick-value-trading-up/) (@tulsky_nhl_2013)

This report will most closely follow the work done by the first three papers listed. As an interesting aside, Eric Tulsky, who wrote the last article listed above in 2013, was hired as General Manager of the Carolina Hurricanes in 2024.
