---
title: "Transform"
author: "Trevor S"
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(stringr) 
library(gt)
```

## Setup

```{r,  message = FALSE, warning = FALSE, cache = TRUE}
# install.packages("tidyverse")
# install.packages("dplyr")
library(tidyverse)
library(dplyr)


source("functions.R") # load functions defined in prior chapters
```

## Code

```{r}
pick_prop <- all_data |> 
  group_by(year) |> 
  mutate(draft_gp = sum(gp), 
         draft_ps = sum(ps), 
         prop_gp = gp / draft_gp, 
         prop_ps = ps / draft_ps) |> 
  group_by(overall) |> 
  summarize(avg_prop_gp = mean(prop_gp), 
            avg_prop_ps = mean(prop_ps),
            .groups = "drop")

est_gp_prop <- rep(0, times = nrow(pick_prop))
est_ps_prop <- rep(0, times = nrow(pick_prop))

for(i in 1:nrow(pick_prop)){
  k <- floor(sqrt(i))
  nearest <- which(abs(seq(1, nrow(pick_prop), 1) - i) <= (k %/% 2)+1)
  total_weight <- sum(pmin(1/abs(i - nearest)^2, 1))
  for(j in nearest){
    weight <- pmin(1/abs(i - j)^2, 1) / total_weight
    est_gp_prop[i] <- est_gp_prop[i] + weight * pick_prop$avg_prop_gp[j]
    est_ps_prop[i] <- est_ps_prop[i] + weight * pick_prop$avg_prop_ps[j]
  }
}

gp_scale_fac <- 1000 / est_gp_prop[[1]]
ps_scale_fac <- 1000 / est_ps_prop[[1]]

knn_model <- data.frame(overall = seq(1, length(est_gp_prop), 1),
                   value_gp = gp_scale_fac * est_gp_prop, 
                   value_ps = ps_scale_fac * est_ps_prop)

ggplot(knn_model, aes(x = overall, y = value_ps)) +
  geom_point()


new_model <- nls(value_ps ~ SSlogis(log(overall), phi1, phi2, phi3), 
                 data = knn_model)

pred_data <- data.frame(overall = seq(1, 224))
predicted_vals <- predict(new_model, pred_data)

pred_data <- mutate(pred_data, value_ps = predicted_vals)

ggplot(pred_data, aes(x = overall, y = value_ps)) + 
  geom_line(lwd = 1.5, col = "red") + 
  geom_point(data = knn_model)

value <- function(overall){
  coefs <- coef(new_model)
  coefs[[1]] / (1 + exp((coefs[[2]] - log(overall))/coefs[[3]]))
}

value(1) - 2*value(8) - value(23)
```
