on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

       - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      - name: Restore R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          install-from: source   # <-- added: forces Linux rebuild of packages

      - name: Force reinstall reactR
        run: Rscript -e 'install.packages("reactR")'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish Book
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: _book
          target: gh-pages