name: Quarto Publish

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      - name: Install basic R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "reactR"), repos = "https://cran.rstudio.com")'
          # Add any extra packages you need for your report/book here
          # Rscript -e 'install.packages(c("tidyverse", "gt", "plotly"))'

      - name: Render Quarto Project
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}